### ISSUE TITLE
Ask some questions

### ISSUE THREAD

**Issue by songzh96** [Sytanek/HBCrestron#2]
Hi Sytanek,
your project is very helpful for me

I has a similar project，it‘s based on homebridge-creskit.
But, the homebridge config quite complicated.
1. So I want to ask How to simplify the configuration? Because i found your project has simplified some config And there are can auto found homekit device.This feature is great.

2. your project "local device" is it a need a raspberry or pc can install homebriddge，“remote device” is cloud?

Best Regards

**Comment by brannon-bowden** [comment]
In regards to the simplification of the configuration and adding the devices, this is actually a feature and all being handled by the HomeBridge-Websocket plugin, so that may be a better place to ask. 

The idea behind local device would be something like a Crestron Dimmer that you want to expose to HomeKit via HomeBridge. 

The idea behind the remote device is if you have a device that is not controlled directly from Crestron, but with a different HomeBridge Plugin. Like a wemo/tp-link bulb/tuya bulb, etc. You would not need to write your own crestron module for this third party device, you can just control via HomeBridge, if HomeBridge can already control it. (Important, the remote device module only works for HomeBridge Devices, not native HomeKit Devices, unfortunately.

**Comment by songzh96** [comment]
Thanks for your answer

the remote is a good idea.

**Comment by songzh96** [comment]
Hi，
Do you know have some method to Implement automatic device addition on the app。
for example，Send a configuration information to the app via crestron professor, the app will automatically add devices (lights, air conditioners, fan devices, etc.) and then control it。

Best Regards
